{{- if .Values.secretKey.create }}
{{- $secretName := default (printf "%s-secret-key" .Release.Name) .Values.secretKey.secretName }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "nebari-superset.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if $existingSecret }}
  SUPERSET_SECRET_KEY: {{ index $existingSecret.data "SUPERSET_SECRET_KEY" }}
  {{- else }}
  SUPERSET_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
